name    'ninech-networkinterfaces'
version '0.1.0'
source 'git://github.com/ninech/puppet-networkinterfaces.git'
author 'David Gurtner <david@nine.ch>'
license 'MIT'
summary 'This module manages network interfaces on Debian based systems'
description 'This module manages network interfaces on Debian based systems'
project_page 'https://github.com/ninech/puppet-networkinterfaces'

dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
